service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
    logs:
      level: info
extensions:
  healthcheckv2:
    use_v2: true
    http:

  jaeger_query:
    base_path: /jaeger
    storage:
      traces: trace_store
      traces_archive: trace_archive_store
    ui:
      config_file: ./cmd/jaeger/config/ui.json

  jaeger_storage:
    backends:
      trace_store:
        badger:
          directories:
            keys: "/data/traces/"
            values: "/data/traces/"
          ephemeral: false
          ttl:
            spans: 48h # 2 days
      trace_archive_store:
        badger:
          directories:
            keys: "/data/traces_archive/"
            values: "/data/traces_archive/"
          ephemeral: false
          ttl:
            spans: 720h # 30 days

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: trace_store