apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-v2
  labels:
    app: jaeger
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown -R 10001:10001 /data && chmod -R 777 /data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: storage
              mountPath: /data
      containers:
        - name: jaeger
          image: jaegertracing/jaeger:2.15.1
          args:
            - "--config"
            - "/cmd/jaeger/config/config.yaml"
          ports:
            - name: ui
              containerPort: 16686
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
          volumeMounts:
            - name: storage
              mountPath: /data
            - name: config
              mountPath: /cmd/jaeger/config

      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: jaeger-v2-data
        - name: config
          configMap:
            name: jaeger-v2-config

