apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


commonLabels:
  app.kubernetes.io/component: jaeger-v2
  app.kubernetes.io/part-of: observability

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

configMapGenerator:
- name: jaeger-v2-config
  files:
    - config.yaml
    - ui.json
