apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: grafana-operator
  namespace: observability
spec:
  interval: 30m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://registry-1.docker.io/bitnamicharts/grafana-operator
  ref:
    semver: "4.4.9"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: observability
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: grafana-operator
    namespace: observability
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values: 
    global:
      imagePullSecrets:
        - image-pulls
    operator:
      resourcesPreset: medium
    grafana:
      config:
        analytics:
          check_for_updates: 'false'
          reporting_enabled: 'false'
        database:
          wal: 'true'
        log:
          level: warn
          mode: console
        security:
          disable_gravatar: 'false'
          allow_embedding: 'true'
        server:
          domain: localhost
          root_url: ${GRAFANA_ROOT_URL:=http://localhost/grafana}
          serve_from_sub_path: 'true'
        users:
          auto_assign_org: 'true'
          auto_assign_org_role: Admin
        auth:
          disable_login_form: 'true'
        auth.proxy:
          enabled: 'true'
          header_name: x-forwarded-email
          header_property: email
          auto_sign_up: 'true'
          sync_ttl: '60'
          whitelist: ""
          headers: "Name:x-forwarded-preferred-username Groups:x-forwarded-groups Role:x-forwarded-groups"
          enable_login_token: 'false'
      