apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-gitops
  namespace: cert-manager
spec:
  wait: true
  prune: true
  interval: 5m
  retryInterval: 3m
  path: cert-manager/gitops
  sourceRef:
    kind: GitRepository
    name: cert-manager
