apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: issuers
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
  prune: true
  interval: 5m
  retryInterval: 3m
  path: cert-manager/helm
  sourceRef:
    kind: GitRepository
    name: observability
