apiVersion:  source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry
spec:
  interval: 15m
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: opentelemetry-operator
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  