apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability-gitops
  namespace: observability
spec:
  prune: true
  interval: 5m
  retryInterval: 3m
  
  path: observability/otel-collector-logging/gitops
  sourceRef:
    kind: GitRepository
    name: observability
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: deployment-config