apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability-otlp
  namespace: observability
spec:
  prune: true
  wait: true
  interval: 15m
  retryInterval: 3m
  path: observability/otel-collector-logging
  sourceRef:
    kind: GitRepository
    name: observability
  components:
    - with-config
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: deployment-config

