apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: OpenTelemetryCollector
    name: otel
    namespace: observability
  patch: |-
    - op: add
      path: /spec/config/exporters/otlp_http~1victorialogs
      value:
        logs_endpoint: http://victoria/victoria/logs/insert/opentelemetry/v1/logs
        
    - op: add
      path: /spec/config/service/pipelines/logs/exporters/-
      value: otlp_http/victorialogs

    - op: add
      path: /spec/config/exporters/otlp_http~1victoriametrics
      value:
        compression: gzip
        encoding: proto
        metrics_endpoint: http://victoria:81/victoria/metrics/opentelemetry/v1/metrics

    - op: add
      path: /spec/config/service/pipelines/metrics/exporters/-
      value: otlp_http/victoriametrics
    
    - op: add
      path: /spec/config/exporters/otlp~1victoriatraces
      value:
        endpoint: http://victoria:4317
        tls:
          insecure: true
    - op: add
      path: /spec/config/service/pipelines/traces/exporters/-
      value: otlp/victoriatraces