apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: otel-collector
spec:
  dependsOn: 
    - name: otel-operator
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: otel-collector
      namespace: observability
  prune: true
  interval: 10m
  retryInterval: 3m
  path: observability/packages/otel-collector/manifests
  sourceRef:
    kind: GitRepository
    name: wac-manifests
  components: []
  postBuild:
    substituteFrom:    []