{
 "title": "System Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "System Traces",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      {
       "id": "service-name",
       "operator": "!~",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "opa-.*" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "WAC-Hospital Error Logs",
   "type": "logs",
   "gridPos": { "h": 28, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"wac-hospital\"} |= `` | json | line_format `{{.log}}` | json | level = `error`"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(rate(k8s_pod_cpu_time_seconds_total[1m]) * 100)",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Pods Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(k8s_pod_memory_usage_bytes)",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  }
 ]
}