apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: mimir
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: grafana-operator
  datasource: 
    uid: wac-metrics
    access: proxy
    name: Metrics
    type: prometheus
    url: "http://mimir-nginx/prometheus"
    database: ""
    user: ""
    jsonData:
      httpMethod: "POST"
    