apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometh
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: grafana-operator
  datasource: 
    uid: prometheus-metrics
    access: proxy
    name: Prometh
    type: prometheus
    url: http://prometheus-gateway:9090
    user: ""
    
    