apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability-resources
  namespace: observability
spec:
  prune: true
  interval: 5m
  retryInterval: 3m
  dependsOn:
  - name: observability-stack
  - name: observability-otlp
  path: observability/grafana-resources
  sourceRef:
    kind: GitRepository
    name: observability
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: deployment-config
