apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability-stack
  namespace: observability
spec:
  prune: true
  wait: true
  interval: 20m
  retryInterval: 3m
  path: observability/grafana-stack
  sourceRef:
    kind: GitRepository
    name: gitops-repo
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: deployment-config