apiVersion:  source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: open-telemetry
  namespace: observability
spec:
  interval: 30m
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: observability
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      interval: 15m
  #releaseName: ""
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: memcached
              namespace: observability
            patch: |
              - op: add
                path: /spec/template/spec/imagePullSecrets
                value:
                  - name: image-pulls
  values:
    fullnameOverride: otel-collector
    mode: daemonset
    config: 
      receivers:
        otlp:
          protocols:
            grpc:
            http:

      exporters:
        logging:
          verbosity: detailed 
          sampling_initial: 5
          sampling_thereafter: 200

      processors:
        batch:

      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging]
    service:
      enabled: true
    image:
      repository: otel/opentelemetry-collector-contrib
      tag: latest
    presets:
      logsCollection:
        enabled: true
      kubernetesAttributes:
        enabled: true
      kubeletMetrics:
        enabled: true
